def menu():
    print("0000000000000Welcome00000000000")
    print("-----Menu-----")
    print("¿Qué desea hacer?")
    print("Calcular el area de un circulo")
    print("Salir")
    print("Por Favor Elija Cuidadosamemte")
    op = input ("Escriba la opcion:")
    op = int(op)
    if op==1: Area_de_circulo()
    else: exit()

def Area_de_circulo():
    import math
    print("")
    print("Para calcular el area de un circulo, necesitamos conocer su radio.")
    print("")
    print("Por favor, Ingrese el valor del radio del circulo:")
    r = float (input())
    print("¡Muy Bien Amigo!")
    print("")
    print("Se esta Haciendo la Solictud de la Operacion")
    print("")
    print("Por favor, espere...")
    print("")
    a= math.pi * (r*r)
    print("Su Respuesta ",r," es: ",a)
    print("")
    menu()
menu()